### ISSUE TITLE
Background image in footer on web mobile doesn't stick to the bottom of the page (multiple reports)

### ISSUE THREAD

**Issue by docsmage** [voiceofrae/RelaxIO#62]
On web mobile, the background of the bottom nav doesn't stick to the bottom of the page. See screenshot:

![screenshot_20170424-101143](https://cloud.githubusercontent.com/assets/6326128/25349873/21d281a0-28d8-11e7-94f6-13f24f7247cc.png)

**Comment by docsmage** [comment]
This was also referenced in #66, separate report pertaining to Android (Samsung Galaxy S4) with both Firefox Beta and Google Chrome.

**Comment by audreytoskin** [comment]
We should maybe reopen this. The footer now stays on the bottom of the page, but it covers up the bottom sound buttons at small enough window sizes.

![screenshot from 2017-05-18 13-12-03](https://cloud.githubusercontent.com/assets/3881885/26221525/ae58b454-3bcb-11e7-9fbf-259a72d0edad.png)

(This screenshot is taken from Firefox for desktop, but it happens on Android too.)
